### PR TITLE
Constants Migration

### PR DESCRIPTION
**Pull request by MostOriginalIGN**

### CODE REVIEW

**Review by Jolteous — COMMENTED** [review]
Looks good, very simple request. Hopefully the rest of the constants will be built upon from Subsystem Migration pull request.

**Review by Jolteous — APPROVED** [review]

**Review by flashrun24 — COMMENTED** [review]
This is good, but I think that it would be better if we just had one Constants.java file, what do you guys think @MostOriginalIGN @Jolteous

**Comment by Jolteous** [comment]
> This is good, but I think that it would be better if we just had one Constants.java file, what do you guys think @MostOriginalIGN @Jolteous

I think multiple is better, since it will be easier to navigate and more efficient, maybe we can incorporate each constants file into a folder containing other mechanisms?

**Comment by flashrun24** [comment]
> > This is good, but I think that it would be better if we just had one Constants.java file, what do you guys think @MostOriginalIGN @Jolteous
> 
> I think multiple is better, since it will be easier to navigate and more efficient, maybe we can incorporate each constants file into a folder containing other mechanisms?

Alright that sounds good so like we would have a file called ShooterConstants.java inside the folder under subsystems/shooter?
And another one called IntakeConstants.java under subystems/intake folder.

**Comment by MostOriginalIGN** [comment]
I will merge this now, but in my branch #6 , I put constants for the wrist inside RobotConstants as a nested class. Will continue this issue there.

**Pull request merged**
